Add Type Lookup Service example using DynamicTypes
eProsima/DDS-Recorder pull request #15
Opened 2023-02-13 11:42 UTC by rsanchez15

2023-02-15 16:22 UTC, irenebm commented on resources/dds/TypeLookupService/types/complete/Complete.h
> +#endif // _FAST_DDS_GENERATED_COMPLETE_H_
EOL

2023-02-15 16:23 UTC, irenebm commented on resources/dds/TypeLookupService/types/complete/CompletePubSubTypes.h
> +#endif // _FAST_DDS_GENERATED_COMPLETE_PUBSUBTYPES_H_
EOF

2023-02-16 07:36 UTC, irenebm requested changes

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/README.md
> +Finally, go to this same folder and run:
```suggestion
Finally, go to this folder and run:
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/README.md
> +1.  Open to terminals
```suggestion
1.  Open two terminals
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/arg_configuration.h
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/main.cpp
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/README.md
> +  -t, --topic <topic_name>          Topic name (Default: DDSTopic).
```suggestion
  -t, --topic <topic_name>          Topic name (Default: /dds/topic).
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/TypeLookupServiceSubscriber.h
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/TypeLookupServiceSubscriber.cpp
> +// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-16 07:36 UTC, irenebm commented on resources/dds/TypeLookupService/TypeLookupServicePublisher.cpp
> +    // Create the DDS Topic
```suggestion
    // Create the DDS Data Writer
```

2023-02-17 08:48 UTC, rsanchez15 commented on resources/dds/TypeLookupService/types/complete/Complete.h
> +#endif // _FAST_DDS_GENERATED_COMPLETE_H_
We do not modify autogenerated files.

2023-02-17 09:16 UTC, irenebm approved these changes

2023-02-17 09:16 UTC, irenebm commented
LGTM

2023-02-20 14:11 UTC, merged