MCAP support [16783]
eProsima/DDS-Recorder pull request #3
Opened 2023-01-11 14:40 UTC by jparisu

2023-01-12 14:15 UTC, rsanchez15 requested changes
- Create `BlankWriter` on `CommonParticipant`.

2023-01-13 07:13 UTC, jparisu commented on ddsrecorder/src/cpp/recorder/mcap/McapHandler.cpp
> +mcap::ChannelId McapHandler::get_channel_id_(
It was because the mutex is required to be taken all along the process, but it is ok like this as well

2023-01-13 07:15 UTC, jparisu commented on ddsrecorder/src/cpp/recorder/mcap/schema.cpp
> +char[20] message
They are 2 different Types. If you mean that there is no internal difference to test the funcionality, that is write (in this case, in PlotJuggler they had differences) , but the example is made like that and I added both.

2023-01-13 07:17 UTC, jparisu commented on ddsrecorder/src/cpp/writer/implementations/recorder/RecorderWriter.cpp
> +            "Error storing data: " << e.what() << " . Continue recording.");
I change the exception so every exception is allowed

2023-01-13 07:44 UTC, rsanchez15 requested changes

2023-01-13 07:44 UTC, rsanchez15 commented on ddsrecorder/src/cpp/participant/implementations/rtps/CommonParticipant.cpp
> +    // }
Do you want to save this commented code?

2023-01-13 07:44 UTC, rsanchez15 commented on ddsrecorder/src/cpp/writer/implementations/recorder/TypeObjectWriter.cpp
> +    // Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
Remove space. 

I didn't check the copyright year in the first review. Should we change it in all files? If that's the case, I'd to it in another PR as that commit will modify every file

2023-01-13 11:29 UTC, rsanchez15 commented on ddsrecorder/src/cpp/writer/implementations/recorder/TypeObjectWriter.cpp
> +    // Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
Fair enough 👍🏼

2023-01-13 11:30 UTC, rsanchez15 approved these changes
LGTM

2023-01-13 11:30 UTC, merged